"use client";

import { ArrowUpRight, CircleDot, Layers3, ScanLine, Sparkles } from "lucide-react";
import { motion } from "framer-motion";
import { Reveal } from "./Reveal";

const principles = [{ icon: Layers3, title: "Make the system visible", text: "A strong identity is more than a logo. I build the rules, rhythms and details that let an idea keep speaking." }, { icon: ScanLine, title: "Give images room", text: "Composition starts with attention. Space, pacing and a precise crop can make a single image feel like a world." }, { icon: CircleDot, title: "Keep the hand in it", text: "Digital polish is better when it still carries a trace of material, texture or an imperfect human gesture." }, { icon: Sparkles, title: "Move with intention", text: "Motion should reveal a relationship or a change in focus. Every transition has a job, then gets out of the way." }];

export default function Vision() { return <section id="practice" className="bg-[#111311] py-24 md:py-36"><div className="section-shell"><Reveal><p className="mono mb-5 text-[var(--accent)]">03 — Practice</p><h2 className="display max-w-2xl text-5xl leading-[.9] md:text-7xl">Design is a<br /><em className="text-white/45">way of looking.</em></h2></Reveal><div className="mt-14 grid gap-px overflow-hidden rounded-3xl border border-white/15 bg-white/15 md:grid-cols-2">{principles.map(({ icon: Icon, title, text }, index) => <motion.article key={title} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: .6, delay: index * .06 }} className="group bg-[#111311] p-7 md:p-10"><div className="flex items-start justify-between"><Icon size={22} strokeWidth={1.2} className="text-[var(--accent)]" /><ArrowUpRight size={18} className="text-white/25 transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></div><h3 className="display mt-12 text-3xl">{title}</h3><p className="mt-4 max-w-sm text-sm leading-relaxed text-white/50">{text}</p></motion.article>)}</div></div></section>; }
